---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install ruby
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - ruby-full
    - ruby-bundler
    - build-essential

- name: add unit file for Puma service
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: 0644
  notify: reload puma

- name: add Puma db config
  template:
    src: db_config.j2
    dest: /home/{{ deploy_user }}/custom_db_config
    mode: 0644
  notify: reload puma

- name: enable puma
  systemd:
    name: puma
    enabled: yes
